Filter datetime
AY2122S2-CS2103T-T12-4/tp pull request #135
Opened 2022-03-25 08:14 UTC by AdrianOngJJ

Need look into my @SuppressWarning in FilterCommand.java

2022-03-25 14:37 UTC, junrong98 commented on src/main/java/seedu/address/logic/commands/FilterCommand.java
> +    private final Predicate predicate;
May I know why you changed `TaskNameContainsKeywordsPredicate` to `Predicate`?

2022-03-25 15:10 UTC, junrong98 requested changes
The changes made currently fix the issue but still uses `SuppressWarnings` . What do you think about the usage @snss231?

Looking through the rest of your code, if this is implemented successfully, will `FilterByDateCommand.java` be removed? Personally, I feel that creating an additional class is not needed as it just increases complication for the users.

Additionally, I'm not sure if I'm using the filter correctly, when I try to filter by date, e.g. `filter d/15-12-2022 2100, 15-12-2022 2100` it does not return any results. If my input is done correctly, it should have shown the 'Brush Teeth ...` task.
 
 Overall, the implementation of filter looks alright. An improvement I would suggest is:
 _Should user be "forced" to input two dates when trying to filter by date, and do user need to put in the time?_
 
To simply this, I think user should just have to input 1 date. And we filter the tasks based on whether its in range. E.g. tasks with a start and end date, we can just check `start_date <= filter_date <= end_date`.

2022-03-26 16:07 UTC, AdrianOngJJ commented
> Additionally, I'm not sure if I'm using the filter correctly, when I try to filter by date, e.g. `filter d/15-12-2022 2100, 15-12-2022 2100` it does not return any results. If my input is done correctly, it should have shown the 'Brush Teeth ...` task.

The logic I used was `isAfter(time)` and `isBefore(time)`, in which both functions are exclusive of the `time` given. In order to make it function the way you've mentioned, I can include the `isEqual(time)` function. [Reference: Java API: Class Local DateTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html)



> Should user be "forced" to input two dates when trying to filter by date, and do user need to put in the time?

I started with 2 input dates as it makes more sense. But perhaps the user wants it to be just that day. The time is so that we can initialise the `LocalDateTime` variable, as all the `LocalDateTime::of` requires timing. [Reference: Java API: Class Local DateTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html)

> To simply this, I think user should just have to input 1 date. And we filter the tasks based on whether its in range. E.g. for tasks with a `start` and `end` date, we can just check `start_date <= filter_date <= end_date`.

I'll look into it.

2022-03-27 16:18 UTC, brian16600 commented
Remember to update UG description/command when done

2022-03-28 10:19 UTC, snss231 commented on src/main/java/seedu/address/logic/parser/FilterCommandParser.java
> +    public List<LocalDateTime> inBetweenDates(String dates) throws DateTimeParseException, ParseException {
For the parser can refer to addcommand and editcommand parser in pr #163

2022-03-28 10:20 UTC, snss231 commented on src/main/java/seedu/address/logic/parser/FilterCommandParser.java
> +    public List<LocalDateTime> inBetweenDates(String dates) throws DateTimeParseException, ParseException {
shud make use of java library for parsing date to avoid bugs

2022-03-28 10:32 UTC, snss231 commented on src/main/java/seedu/address/logic/commands/FilterCommand.java
>          model.updateFilteredTaskList(predicate);
yea this is right, `Predicate<Task>` also can

2022-03-28 18:01 UTC, closed without merging